// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKQjgDbLxbxEwvAWKYXz_bIVQrHdBs9ag',
    appId: '1:1001159149987:web:cf79fe83322ab6449c7216',
    messagingSenderId: '1001159149987',
    projectId: 'ahseno-8090c',
    authDomain: 'ahseno-8090c.firebaseapp.com',
    storageBucket: 'ahseno-8090c.appspot.com',
    measurementId: 'G-D51H1F058X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjce_SB7HcRSVbuSJia0MfoZQe7Ug74yI',
    appId: '1:1001159149987:android:047dc2364e0cea4c9c7216',
    messagingSenderId: '1001159149987',
    projectId: 'ahseno-8090c',
    storageBucket: 'ahseno-8090c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8xtNREQrxpS1b-z7pKpF7F_uoZD5sOU0',
    appId: '1:1001159149987:ios:276dca02d00844b19c7216',
    messagingSenderId: '1001159149987',
    projectId: 'ahseno-8090c',
    storageBucket: 'ahseno-8090c.appspot.com',
    iosClientId: '1001159149987-rbmgk94ln9vrlc1cjnnpevsf7b1mdi2d.apps.googleusercontent.com',
    iosBundleId: 'com.example.designapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA8xtNREQrxpS1b-z7pKpF7F_uoZD5sOU0',
    appId: '1:1001159149987:ios:276dca02d00844b19c7216',
    messagingSenderId: '1001159149987',
    projectId: 'ahseno-8090c',
    storageBucket: 'ahseno-8090c.appspot.com',
    iosClientId: '1001159149987-rbmgk94ln9vrlc1cjnnpevsf7b1mdi2d.apps.googleusercontent.com',
    iosBundleId: 'com.example.designapp',
  );
}
